name: "Build and Deploy to Cloud Run"

on:
  push:
    branches:
      - "develop"

env:
  PROJECT_ID: "${{ secrets.PROJECT_ID }}"
  GCR_REGION: "${{ secrets.GCR_REGION }}"
  GAR_IMAGE_NAME: "${{ secrets.GAR_IMAGE_NAME }}"
  GAR_REPO_NAME: "${{ secrets.GAR_REPO_NAME }}"
  GAR_REGION: "${{ secrets.GAR_REGION }}"
  GCR_SERVICE: "${{ secrets.GCR_SERVICE }}"

jobs:
  deploy:
    runs-on: "self-hosted"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Authenticate to GCP"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDS }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Docker Auth To GAR"
        run: |
          gcloud auth configure-docker "${{env.GAR_REGION}}-docker.pkg.dev"

      - name: "Build and Push To GAR"
        run: |-
          DOCKER_TAG="${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/${{ env.GAR_IMAGE_NAME }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: Deploy to Cloud Run
        run: |
          echo SERVICE_NAME ${{ env.GCR_SERVICE }}
          gcloud run deploy ${{ env.GCR_SERVICE }} \
            --image ${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/${{ env.GAR_IMAGE_NAME }}:${{ github.sha }} \
            --platform managed \
            --memory 8Gi \
            --cpu 2 \
            --timeout=1800s \
            --region ${{ env.GCR_REGION }} \
            --port 8000 \
            --allow-unauthenticated
      - name: "Show output"
        run: |2-
          echo ${{ steps.deploy.outputs.url }}
